[package]
name = "boron"
version = "0.0.1"
authors = ["Aloïs Micard <alois@micard.lu>"]
edition = "2018"
license = "GPL-3.0-only"
repository = "https://github.com/creekorful/boron"
readme = "README.md"

[dependencies]

[dependencies.clap]
version = "2.33.1"
default-features = false
