[package]
name = "boron"
version = "0.0.1"
authors = ["Aloïs Micard <alois@micard.lu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
failure = "0.1.8"
clap = "2.33.1"